Repository Book-Mile/frontend, pull requests merged in 2024-12, with the labels that each got.

#25 chore: Add GitHub Actions workflow configuration
  .github/workflows/front_ci.yml
Labels: 환경설정

#22 feat,design: 그룹 생성 다이얼로그 생성과 그에 관한 기능들 추가
  index.html
  src/App.jsx
  src/animations/animations.jsx
  src/components/LGButton/LGButton.jsx
  src/components/makingGroupComponents/GroupCards.jsx
  src/components/modalButton/ModalButtonCancel.jsx
  src/components/modalButton/ModalButtonOk.jsx
  src/components/popup/MakingGroupPopup.jsx
  src/components/popup/RightPopup_one.jsx
  src/components/popup/RightPopup_two.jsx
  src/components/popup/SelectedChapter.jsx
  src/components/popup/SelectedMine.jsx
  src/components/popup/SelectedNumber.jsx
  src/components/popup/SelectedPages.jsx
  src/hooks/makingGroupForm.jsx
  src/hooks/useModalSelectedGroup.jsx
  src/pages/CheckPointRecordPage.jsx
  src/styled_components/CheckPointRecordPageStyle.jsx
  src/styled_components/popupStyle.jsx
  src/theme.js
Labels: 디자인, 기능구현

#29 design/#28 전체 레이아웃 설정
  package.json
  src/App.jsx
  src/index.css
Labels: 디자인

#23 design/#23 NavBar 퍼블리싱 완료
  public/images/profile.png
  src/App.css
  src/App.jsx
  src/components/NavBar.jsx
  src/components/icons/NotifBell.jsx
  src/index.css
  src/theme.js
Labels: 디자인
