Repository Book-Mile/frontend, pull requests merged in 2025-02, with the labels that each got.

#110 Issue/#109 로그인, 회원가입창 위치 문제 해결 등
  src/api/Pages/MyPageRequest.jsx
  src/assets/cancel.svg
  src/components/EndedBookList.jsx
  src/components/NavBar.jsx
  src/components/PendingBookList.jsx
  src/components/ProgressBookList.jsx
  src/components/modeTag/ModeTag.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
  src/styled_components/popupStyle.jsx
Labels: 이슈 해결

#112 feat/#111 그룹 종료 모달 api 연동
  src/api/Popup/EndGroupPopupSubmit.jsx
  src/components/popup/EndGroupPopup/EndGroupPopup.jsx
Labels: 기능구현

#122 Feat/#115 체크포인트 기록 api 연동
  src/api/Popup/CheckpointRecordPopupSubmit.jsx
  src/components/popup/CheckpointRecordPopup/CheckpointRecordPopup.jsx
  src/pages/BookProgress.jsx
Labels: 기능구현

#128 feat: 소셜 로그인 연동
  src/App.jsx
  src/api/Pages/LoginRequest.jsx
  src/pages/Login.jsx
Labels: 기능구현

#132 feat/#131 api 왜 다 안됨 + 모달창 크기 맞추기
  src/api/Pages/CheckPointRecordRequest.jsx
  src/api/Popup/RatingPopupSubmit.jsx
  src/api/Popup/RightPopup_oneRequestList.jsx
  src/components/popup/MakingGroupPopup/RightPopup_one.jsx
  src/components/popup/MakingGroupPopup/SelectedChapter.jsx
  src/components/popup/MakingGroupPopup/SelectedMine.jsx
  src/components/popup/MakingGroupPopup/SelectedNumber.jsx
  src/components/popup/MakingGroupPopup/SelectedPages.jsx
  src/components/popup/RatingPopup/RatingPopup.jsx
  src/pages/CheckPointRecordPage.jsx
  src/styled_components/popupStyle.jsx
Labels: 디자인, 기능구현

#134 feat/#133 기록모달 이미지 업로드 api 연동
  src/api/Popup/CheckpointRecordPopupSubmit.jsx
  src/components/popup/CheckpointRecordPopup/CheckpointRecordPopup.jsx
Labels: 기능구현

#136 feat/#135 sns 연동 페이지 api 연동
  src/api/Pages/EditMyInfoRequest.jsx
  src/api/Pages/SNSManageRequest.jsx
  src/components/NavBar.jsx
  src/pages/EditMyInfo.jsx
  src/pages/SNSManage.jsx
Labels: 기능구현

#138 feat/#137 프로필 이미지 변경 기능 구현
  src/api/Pages/EditMyInfoRequest.jsx
  src/assets/EditMyInfoAssets/editImgBtn.svg
  src/components/EndedBookList.jsx
  src/components/PendingBookList.jsx
  src/components/ProgressBookList.jsx
  src/components/Ranking/SubItem.jsx
  src/pages/EditMyInfo.jsx
  src/pages/MyPage.jsx
  src/pages/ProfileModal.jsx
Labels: 기능구현

#140 feat/#139 로그인 리퀘스트 대기 시간 동안 로딩화면 출력
  src/animations/Loading.jsx
  src/api/Pages/LoginRequest.jsx
  src/pages/Login.jsx
Labels: 기능구현

#142 feat/#141 회원가입 페이지 로딩 화면 추가 및 로직 개선
  src/api/Pages/SignUpRequest.jsx
  src/pages/SignUp.jsx
Labels: 리팩토링, 기능구현
