Repository Book-Mile/frontend, pull requests merged in 2025-01, with the labels that each got.

#49 Design/#37 검색 결과 페이지 퍼블리싱
  .github/workflows/front_ci.yml
  public/images/aladinlogo.png
  src/App.jsx
  src/assets/search/search.svg
  src/components/search/BookLabel.jsx
  src/components/search/Rating.jsx
  src/components/search/SearchBar.jsx
  src/pages/SearchResults.jsx
Labels: 디자인

#56 design/#55 로딩 애니메이션 구현 완료
  public/images/1481.png
  src/animations/Loding.jsx
Labels: 디자인

#54 Design/#50 대기방 퍼블리싱
  public/images/cover.png
  src/App.jsx
  src/components/GroupedPeople.jsx
  src/components/button/whitebutton.jsx
  src/components/search/BookLabel.jsx
  src/index.css
  src/pages/Lobby.jsx
  src/styled_components/popupStyle.jsx
  src/theme.js
Labels: 디자인

#62 feat/#53 체크포인트 모달에 파일 업로드 기능 구현
  src/components/popup/CheckpointRecordPopup/CheckpointRecordPopup.jsx
  src/styled_components/popupStyle.jsx
Labels: 디자인, 기능구현

#65 refactor/#64 로그인, 회원가입 페이지 모달창으로 변경
  src/App.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
Labels: 리팩토링

#69 fix: 탈퇴 모달 디자인 개선
  src/components/LGButton/LGButton.jsx
  src/components/popup/SecessionUserPopup/SecessionUserPopup.jsx
Labels: 이슈 해결, 디자인

#67 design/#66 SNS 연동 관리 페이지 퍼블리싱
  src/App.jsx
  src/assets/Alert/ok.svg
  src/assets/Alert/warning.svg
  src/assets/Toggle/ToggleOff.svg
  src/assets/Toggle/ToggleOn.svg
  src/components/popup/EndGroupPopup/EndGroupPopup.jsx
  src/components/popup/RegisterCompletePopup/RegisterCompletePopup.jsx
  src/pages/SNSManage.jsx
Labels: 디자인

#72 Feat/#61 api 설계와 react-error-boundary
  package-lock.json
  package.json
  src/App.jsx
  src/api/Pages/CheckPointRecordRequest.jsx
  src/api/Popup/JoinGroupPopupSubmit.jsx
  src/api/Popup/MakingGroupPopupSubmit.jsx
  src/api/Popup/RightPopup_oneRequestList.jsx
  src/components/popup/JoinGroupPopup/JoinGroupPopup.jsx
  src/components/popup/MakingGroupPopup/MakingGroupPopup.jsx
  src/components/popup/MakingGroupPopup/RightPopup_one.jsx
  src/components/popup/MakingGroupPopup/SelectedChapter.jsx
  src/components/popup/MakingGroupPopup/SelectedMine.jsx
  src/components/popup/MakingGroupPopup/SelectedNumber.jsx
  src/components/popup/MakingGroupPopup/SelectedPages.jsx
  src/components/popup/SecessionUserPopup/SecessionUserPopup.jsx
  src/data/joinGroupPopupData.jsx
  src/hooks/makingGroupForm.jsx
  src/hooks/useErrorHandling.jsx
  src/hooks/useModalSelectedGroup.jsx
  src/pages/CheckPointRecordPage.jsx
  src/styled_components/popupStyle.jsx
  src/utils/ErrorFallback.jsx
  vite.config.js
Labels: 기능구현

#78 design/#77 마이페이지 퍼블리싱 및 NavBar영역 명확히 수정
  src/App.jsx
  src/assets/EditMyInfoAssets/Profile.svg
  src/assets/EditMyInfoAssets/email.svg
  src/assets/EditMyInfoAssets/password.svg
  src/assets/EditMyInfoAssets/sns.svg
  src/assets/ModeTagAssets/Page.svg
  src/assets/ModeTagAssets/Speed.svg
  src/assets/MyInfoAssets/edit.svg
  src/assets/bookImg.png
  src/assets/bookImg2.png
  src/assets/bookImg3.png
  src/assets/bookImg4.png
  src/assets/profile.png
  src/components/EndedBookList.jsx
  src/components/NavBar.jsx
  src/components/PendingBookList.jsx
  src/components/ProgressBookList.jsx
  src/components/modeTag/ModeTag.jsx
  src/components/popup/RegisterCompletePopup/RegisterCompletePopup.jsx
  src/index.css
  src/pages/EditMyInfo.jsx
  src/pages/MyPage.jsx
Labels: 이슈 해결, 디자인, 기능구현

#85 fix: 병합 충돌 해결
  src/App.jsx
  src/styled_components/CheckPointRecordPageStyle.jsx
Labels: 이슈 해결

#87 Design/#82 로그인, 회원가입, 마이페이지 구성요소 변경
  src/App.css
  src/components/LGButton/LGButton.jsx
  src/pages/EditMyInfo.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  src/styled_components/makingGroupPageStyle.jsx
Labels: 이슈 해결, 디자인
